# Generated by Django 4.1.5 on 2023-01-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_worked',
            field=models.BooleanField(default=True, verbose_name='Выход на работу'),
        ),
        migrations.AddField(
            model_name='user',
            name='tg_chat_id',
            field=models.CharField(max_length=64, null=True, verbose_name='ID чата Телеграм'),
        ),
    ]
