# Generated by Django 4.1.5 on 2023-01-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_delivery_delivered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(choices=[('QLY', 'Как можно скорее'), ('FRS', 'с 10:00 до 12:00'), ('SEC', 'с 12:00 до 14:00'), ('THR', 'с 14:00 до 16:00'), ('FOU', 'с 16:00 до 18:00'), ('FIF', 'с 18:00 до 20:00')], db_index=True, default='QLY', max_length=3, verbose_name='Время доставки'),
        ),
    ]
