# Generated by Django 3.2.16 on 2023-01-20 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_order_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('AC', 'Принят'), ('PD', 'Оплачен'), ('AS', 'Сборка'), ('DL', 'Доставка'), ('FN', 'Завершен'), ('CN', 'Отменен')], db_index=True, default='AC', max_length=2, verbose_name='Статус заказа'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=4, verbose_name='Последние 4 цифры номера карты')),
                ('payment_id', models.CharField(blank=True, max_length=50, verbose_name='ID платежа')),
                ('status', models.CharField(choices=[('PND', 'Ожидает подтверждения'), ('SCS', 'Оплачен'), ('CNC', 'Отменен')], default='PND', max_length=3, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='website.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
