# Generated by Django 4.1.5 on 2023-01-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20230120_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.CharField(max_length=50, verbose_name='Последние 4 цифры номера карты'),
        ),
    ]
