# Generated by Django 4.1.5 on 2023-01-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_payment_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='PaymentOrder',
        ),
    ]
